services:
  artbound_python:
    build: .
    image: docker_status:latest
    container_name: docker-status
    ports:
      - 127.0.0.1:1111:1111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/config.json:/app/config.json:ro
