services:
  app:
    build: .
    image: ghcr.io/birabittoh/docker-status:main
    container_name: docker-status
    ports:
      - 127.0.0.1:1111:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/app/config.json:ro
