services:
  artbound_python:
    build: .
    image: docker_status:latest
    container_name: docker-status
    ports:
      - 127.0.0.1:1111:1111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/config.json:/app/config.json:ro
    healthcheck:
      test: wget -nv --tries=1 --spider http://localhost:1111/stats || exit 1
      interval: 30s
      timeout: 5s
      retries: 2